// Defining the action types
export const ADD_SPONSORS = 'ADD_SPONSORS';
export const SPONSORS_LOADING = 'SPONSORS_LOADING';
export const SPONSORS_FAILED = 'SPONSORS_FAILED';

export const ADD_MEMBERS = 'ADD_MEMBERS';
export const MEMBERS_LOADING = 'MEMBERS_LOADING';
export const MEMBERS_FAILED = 'MEMBERS_FAILED';

export const ADD_FAQS = 'ADD_FAQS';
export const FAQS_LOADING = 'FAQS_LOADING';
export const FAQS_FAILED = 'FAQS_FAILED';

export const ADD_VOLUNTEERS = 'ADD_VOLUNTEERS';
export const VOLUNTEERS_LOADING = 'VOLUNTEERS_LOADING';
export const VOLUNTEERS_FAILED = 'VOLUNTEERS_FAILED';


